sudo: required
services:
  - docker
language: bash
script:
  # build image
  - docker build -t fbrx/nodeaws nodeaws/

  # test image
  - docker run fbrx/nodeaws aws --version

  # push image
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push fbrx/nodeaws
